version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads
    restart: unless-stopped
    environment:
      - NODE_ENV=production